### ISSUE TITLE
macOS Sierra, doesn't work

### ISSUE THREAD

**Issue by viktorkovarik** [anatasof/homebrew-epsxe#1]
Installed via brew install epsxe.rb, installation worked well, but when I type epsxe into terminal, it outputs: Killed: 9. If I run echo $? it returns error value 137.

Thanks for making OSX version ! :-)

**Comment by anatasof** [comment]
Hi! thanks for pointing out this issue 👍. But unfortunately, we will have to face this macOS sierra related issue at the moment. Hopefully we'll get it fixed on 2.0.6.

**Comment by xaviermerino** [comment]
This is how I solved it in my Mac. 
I am assuming that your brew directory is standard and you haven't moved it from `/usr/local/Cellar`.

First we install `upx`:
```
brew install upx
```

I am assuming you have already installed epsxe with the instructions provided in this repository. If you did then it is located in the following directory: `/usr/local/Cellar/epsxe/2.0.5/bin`. We then execute the following commands:

```
cd /usr/local/Cellar/epsxe/2.0.5/bin
sudo chmod 777 ./epsxe
sudo upx -d ./epsxe
```

You can now run it by just typing `epsxe` in the command line.

**Comment by anatasof** [comment]
Thanks @xaviermerino , this solves the problem running on macOS sierra. May I add it on readme.md?

**Comment by xaviermerino** [comment]
Sure go ahead!

**Comment by anatasof** [comment]
@xaviermerino Thanks a heap!

**Comment by The1andONLYdave** [comment]
Also on High Sierra this fix works. Took me an hour of google-ing. Maybe someone can mention this on the download page or print when running the ruby-installscript?

**Comment by hanggrian** [comment]
This fix is still needed in Catalina, many thanks and long live classic PS!
