### ISSUE TITLE
macOS High Sierra - Segmentation fault: 11

### ISSUE THREAD

**Issue by NicFontana** [anatasof/homebrew-epsxe#2]
I'm trying to run it on an iMac Late 2012 with macOS High Sierra, but after I open a game by selecting "Run ISO" it crashes and give me this message:
```
* ePSXe change dir to /Users/raga/.epsxe/
 * Running ePSXe emulator version 2.0.5. 
Elegido /Users/raga/Documents/Rom/PS1/crash.img
 * Memory handlers init. 
 * ePSXe: PSX BIOS loaded [/Users/raga/.epsxe/bios/scph1001.bin]. 
 * Loading ISO Format [MDF/BIN/IMG2352] ok
 * First/Last track: 1 1
 * Track 1: (DATA)  - Start 1: (00,02,00) -  Length 15:47
 * NTSC cdrom detected. (SLU__006.27) 
 * Init gpu core 
 * GPU supports GTE Accurate
 * Init OpenGLv2...
OpenGL Screen Resolution 800x600 Ratio: 4:3Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 640M OpenGL Engine
 * Open gpu[0] 
 * Linux input init error. 
 * Init core spu ...  ok 
Segmentation fault: 11
```

Any suggestions?
Thanks in advance

**Comment by The1andONLYdave** [comment]
Also on Mojave with 2.0.5:
epsxe
 * ePSXe change dir to /Users/david-lee/.epsxe/
 * Running ePSXe emulator version 2.0.5.

(process:7466): Gtk-WARNING **: 10:34:50.108: Locale not supported by C library.
	Using the fallback 'C' locale.
Elegido /Users/david-lee/Desktop/windows final fantasy/ffviii/ff8 kopierschutzwegpatched/ff8-201.iso
 * Memory handlers init.
 * ePSXe: PSX BIOS loaded [/Users/david-lee/Desktop/windows final fantasy/ffviii/scph5502.bin].
 * Loading ISO Format [MDF/BIN/IMG2352] ok
 * First/Last track: 1 1
 * Track 1: (DATA)  - Start 1: (00,02,00) -  Length 65:26
 * PAL cdrom detected. (SLES_120.82)
 * Subchannel support from fake .sbi.
 * Init gpu core
 * GPU supports GTE Accurate
 * Init OpenGLv2...
OpenGL Screen Resolution 800x600 Ratio: 4:3Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 6000
 * Open gpu[0]
 * Linux input init error.
 * Init core spu ...  ok
[1]    7466 segmentation fault  epsxe

**Comment by akudaniy** [comment]
Same issue here. Since High Sierra upto recently Mojave, I've been experiencing Segmentation Fault Error. I guess it's something about memory segmentation issue. 


>  * ePSXe change dir to /Users/murdanieko/.epsxe/
>  * Running ePSXe emulator version 2.0.5. 
> 
> (process:732): Gtk-WARNING **: 19:43:11.981: Locale not supported by C library.
> 	Using the fallback 'C' locale.
>  * Memory handlers init. 
>  * ePSXe: PSX BIOS loaded [bios/SCPH-1001.bin]. 
>  * Init internal cdrom ... CD_Init: open of "" failed (2)
>  * Init gpu core 
>  * GPU supports GTE Accurate
>  * Init OpenGLv2...
> OpenGL Screen Resolution 800x600 Ratio: 4:3Vendor: Intel Inc.
> Renderer: Intel HD Graphics 4000 OpenGL Engine
>  * Open gpu[0] 
>  * Linux input init error. 
>  * Init core spu ...  ok 
> Segmentation fault: 11
>

**Comment by kaiokmo** [comment]
Any news about this?

**Comment by khrisnaa3** [comment]
same issue here.. any solution ?

**Comment by akudaniy** [comment]
I thought the solution was **waiting until Apple released macOS Catalina**. Last week I updated to 10.15. Today I ran epsxe and it worked like a charm. No more segmentation fault: 11. 

Just like the old days of El Capitan.

**Comment by anatasof** [comment]
> I thought the solution was **waiting until Apple released macOS Catalina**. Last week I updated to 10.15. Today I ran epsxe and it worked like a charm. No more segmentation fault: 11.
> 
> Just like the old days of El Capitan.

You're right @akudaniy . I've just tried to run it on Catalina and it works without problem.

Closing this Issue for now.

<img width="777" alt="Screen Shot 2019-11-07 at 16 15 28" src="https://user-images.githubusercontent.com/2198741/68376019-72177800-017a-11ea-974d-0068cae62829.png">
